Domain attributes
Arquisoft/Agents_i2b pull request #11
Opened 2018-02-13 21:30 UTC by carmee-en

Solution for issue #8 .
Domain and test classes updated to meet new attribute requirements. Tests should pass (although not very exhaustive).

Possible new issues:
- Change attribute 'identifier' to 'id' to match the requirements
- Change 'location' attribute type (currently double[ ])
- Unify coding styles

2018-02-14 14:41 UTC, alejgh requested changes
Looks good to me! It would be great if you could add a simple location test (and maybe also a kind test) to test the new attributes, since we are losing quite a lot of test coverage. You can see here the methods that are not tested right now in the classes you modified:
https://codecov.io/gh/Arquisoft/Agents_i2b/src/64d60a3133f48270808d2934a3673ff74bcf2601/src/main/java/domain/AgentInfo.java
https://codecov.io/gh/Arquisoft/Agents_i2b/src/64d60a3133f48270808d2934a3673ff74bcf2601/src/main/java/domain/Agent.java

You don't need to do exhaustive tests, something simple will do. It's just to avoid losing so much code coverage already in the first merge.

2018-02-14 14:41 UTC, alejgh commented on src/main/java/view/ParticipantsController.java
> +//            model.addAttribute("lName", info.getLastName());
Can you remove these comments please?

2018-02-14 17:19 UTC, alejgh approved these changes

2018-02-14 17:23 UTC, merged

2018-02-16 19:30 UTC, miguelff commented on src/main/java/domain/Agent.java
> +	@Override
Mind formatting the code? ;-)

2018-02-16 19:35 UTC, miguelff commented on src/test/java/domain_tests/UserTest.java
> +    public void nameTest(){
Usually, IDEs have support for automatic generation of getters and setters. For that reason, and even though it increases coverage, testing these code-paths could be omitted as they don't actually exercise logic that is prone to error. 

In words of Jeff Atwood, [The Best Code is No Code At All](https://blog.codinghorror.com/the-best-code-is-no-code-at-all/)

2018-02-16 19:38 UTC, miguelff commented
GitHub Pro-tip: If in the PR description you reference an issue prefixed with the words "Closes" or "Fixes", it will automatically close the issue when the PR is merged. Example:

A PR containing `This PR fixes #8` in the description, will close the issue #8 when merged.